//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.09 at 10:19:56 PM MDT 
//


package org.smartreaction.boardgamegeek.xml.collection;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}usersrated"/>
 *         &lt;element ref="{}average"/>
 *         &lt;element ref="{}bayesaverage"/>
 *         &lt;element ref="{}stddev"/>
 *         &lt;element ref="{}median"/>
 *         &lt;element ref="{}ranks"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usersrated",
    "average",
    "bayesaverage",
    "stddev",
    "median",
    "ranks"
})
@XmlRootElement(name = "rating")
public class Rating {

    @XmlElement(required = true)
    protected Usersrated usersrated;
    @XmlElement(required = true)
    protected Average average;
    @XmlElement(required = true)
    protected Bayesaverage bayesaverage;
    @XmlElement(required = true)
    protected Stddev stddev;
    @XmlElement(required = true)
    protected Median median;
    @XmlElement(required = true)
    protected Ranks ranks;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String value;

    /**
     * Gets the value of the usersrated property.
     * 
     * @return
     *     possible object is
     *     {@link Usersrated }
     *     
     */
    public Usersrated getUsersrated() {
        return usersrated;
    }

    /**
     * Sets the value of the usersrated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Usersrated }
     *     
     */
    public void setUsersrated(Usersrated value) {
        this.usersrated = value;
    }

    /**
     * Gets the value of the average property.
     * 
     * @return
     *     possible object is
     *     {@link Average }
     *     
     */
    public Average getAverage() {
        return average;
    }

    /**
     * Sets the value of the average property.
     * 
     * @param value
     *     allowed object is
     *     {@link Average }
     *     
     */
    public void setAverage(Average value) {
        this.average = value;
    }

    /**
     * Gets the value of the bayesaverage property.
     * 
     * @return
     *     possible object is
     *     {@link Bayesaverage }
     *     
     */
    public Bayesaverage getBayesaverage() {
        return bayesaverage;
    }

    /**
     * Sets the value of the bayesaverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bayesaverage }
     *     
     */
    public void setBayesaverage(Bayesaverage value) {
        this.bayesaverage = value;
    }

    /**
     * Gets the value of the stddev property.
     * 
     * @return
     *     possible object is
     *     {@link Stddev }
     *     
     */
    public Stddev getStddev() {
        return stddev;
    }

    /**
     * Sets the value of the stddev property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stddev }
     *     
     */
    public void setStddev(Stddev value) {
        this.stddev = value;
    }

    /**
     * Gets the value of the median property.
     * 
     * @return
     *     possible object is
     *     {@link Median }
     *     
     */
    public Median getMedian() {
        return median;
    }

    /**
     * Sets the value of the median property.
     * 
     * @param value
     *     allowed object is
     *     {@link Median }
     *     
     */
    public void setMedian(Median value) {
        this.median = value;
    }

    /**
     * Gets the value of the ranks property.
     * 
     * @return
     *     possible object is
     *     {@link Ranks }
     *     
     */
    public Ranks getRanks() {
        return ranks;
    }

    /**
     * Sets the value of the ranks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ranks }
     *     
     */
    public void setRanks(Ranks value) {
        this.ranks = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
