//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.09 at 10:19:56 PM MDT 
//

package org.smartreaction.boardgamegeek.xml.collection;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="fortrade" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="lastmodified" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="own" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="preordered" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="prevowned" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="want" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="wanttobuy" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="wanttoplay" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="wishlist" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "status")
public class Status {

    @XmlAttribute(required = true)
    protected String fortrade;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lastmodified;
    @XmlAttribute(required = true)
    protected String own;
    @XmlAttribute(required = true)
    protected String preordered;
    @XmlAttribute(required = true)
    protected String prevowned;
    @XmlAttribute(required = true)
    protected String want;
    @XmlAttribute(required = true)
    protected String wanttobuy;
    @XmlAttribute(required = true)
    protected String wanttoplay;
    @XmlAttribute(required = true)
    protected String wishlist;

    /**
     * Gets the value of the fortrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFortrade() {
        return fortrade;
    }

    /**
     * Sets the value of the fortrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFortrade(String value) {
        this.fortrade = value;
    }

    /**
     * Gets the value of the lastmodified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastmodified() {
        return lastmodified;
    }

    /**
     * Sets the value of the lastmodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastmodified(String value) {
        this.lastmodified = value;
    }

    /**
     * Gets the value of the own property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwn() {
        return own;
    }

    /**
     * Sets the value of the own property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwn(String value) {
        this.own = value;
    }

    /**
     * Gets the value of the preordered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreordered() {
        return preordered;
    }

    /**
     * Sets the value of the preordered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreordered(String value) {
        this.preordered = value;
    }

    /**
     * Gets the value of the prevowned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevowned() {
        return prevowned;
    }

    /**
     * Sets the value of the prevowned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevowned(String value) {
        this.prevowned = value;
    }

    /**
     * Gets the value of the want property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWant() {
        return want;
    }

    /**
     * Sets the value of the want property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWant(String value) {
        this.want = value;
    }

    /**
     * Gets the value of the wanttobuy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanttobuy() {
        return wanttobuy;
    }

    /**
     * Sets the value of the wanttobuy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanttobuy(String value) {
        this.wanttobuy = value;
    }

    /**
     * Gets the value of the wanttoplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanttoplay() {
        return wanttoplay;
    }

    /**
     * Sets the value of the wanttoplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanttoplay(String value) {
        this.wanttoplay = value;
    }

    /**
     * Gets the value of the wishlist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWishlist() {
        return wishlist;
    }

    /**
     * Sets the value of the wishlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWishlist(String value) {
        this.wishlist = value;
    }

}
