//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.20 at 08:53:40 PM MDT 
//

package org.smartreaction.boardgamegeek.xml.game;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}thumbnail"/>
 *         &lt;element ref="{}image"/>
 *         &lt;element ref="{}name" maxOccurs="unbounded"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}yearpublished"/>
 *         &lt;element ref="{}minplayers"/>
 *         &lt;element ref="{}maxplayers"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}minage"/>
 *           &lt;element ref="{}playingtime"/>
 *           &lt;element ref="{}poll"/>
 *         &lt;/choice>
 *         &lt;element ref="{}link" maxOccurs="unbounded"/>
 *         &lt;element ref="{}statistics"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "thumbnail",
    "image",
    "name",
    "description",
    "yearpublished",
    "minplayers",
    "maxplayers",
    "minageOrPlayingtimeOrPoll",
    "link",
    "statistics"
})
@XmlRootElement(name = "item")
public class Item {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String thumbnail;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String image;
    @XmlElement(required = true)
    protected List<Name> name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected Yearpublished yearpublished;
    @XmlElement(required = true)
    protected Minplayers minplayers;
    @XmlElement(required = true)
    protected Maxplayers maxplayers;
    @XmlElements({
        @XmlElement(name = "minage", type = Minage.class),
        @XmlElement(name = "playingtime", type = Playingtime.class),
        @XmlElement(name = "poll", type = Poll.class)
    })
    protected List<Object> minageOrPlayingtimeOrPoll;
    @XmlElement(required = true)
    protected List<Link> link;
    @XmlElement(required = true)
    protected Statistics statistics;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;

    /**
     * Gets the value of the thumbnail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * Sets the value of the thumbnail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbnail(String value) {
        this.thumbnail = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Name }
     * 
     * 
     */
    public List<Name> getName() {
        if (name == null) {
            name = new ArrayList<Name>();
        }
        return this.name;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the yearpublished property.
     * 
     * @return
     *     possible object is
     *     {@link Yearpublished }
     *     
     */
    public Yearpublished getYearpublished() {
        return yearpublished;
    }

    /**
     * Sets the value of the yearpublished property.
     * 
     * @param value
     *     allowed object is
     *     {@link Yearpublished }
     *     
     */
    public void setYearpublished(Yearpublished value) {
        this.yearpublished = value;
    }

    /**
     * Gets the value of the minplayers property.
     * 
     * @return
     *     possible object is
     *     {@link Minplayers }
     *     
     */
    public Minplayers getMinplayers() {
        return minplayers;
    }

    /**
     * Sets the value of the minplayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Minplayers }
     *     
     */
    public void setMinplayers(Minplayers value) {
        this.minplayers = value;
    }

    /**
     * Gets the value of the maxplayers property.
     * 
     * @return
     *     possible object is
     *     {@link Maxplayers }
     *     
     */
    public Maxplayers getMaxplayers() {
        return maxplayers;
    }

    /**
     * Sets the value of the maxplayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Maxplayers }
     *     
     */
    public void setMaxplayers(Maxplayers value) {
        this.maxplayers = value;
    }

    /**
     * Gets the value of the minageOrPlayingtimeOrPoll property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the minageOrPlayingtimeOrPoll property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMinageOrPlayingtimeOrPoll().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Minage }
     * {@link Playingtime }
     * {@link Poll }
     * 
     * 
     */
    public List<Object> getMinageOrPlayingtimeOrPoll() {
        if (minageOrPlayingtimeOrPoll == null) {
            minageOrPlayingtimeOrPoll = new ArrayList<Object>();
        }
        return this.minageOrPlayingtimeOrPoll;
    }

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Link }
     * 
     * 
     */
    public List<Link> getLink() {
        if (link == null) {
            link = new ArrayList<Link>();
        }
        return this.link;
    }

    /**
     * Gets the value of the statistics property.
     * 
     * @return
     *     possible object is
     *     {@link Statistics }
     *     
     */
    public Statistics getStatistics() {
        return statistics;
    }

    /**
     * Sets the value of the statistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statistics }
     *     
     */
    public void setStatistics(Statistics value) {
        this.statistics = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
