//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.25 at 09:28:35 PM MDT 
//

package org.smartreaction.boardgamegeek.xml.oldapi.collection;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}rating"/>
 *       &lt;/sequence>
 *       &lt;attribute name="maxplayers" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="minplayers" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="numowned" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="playingtime" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rating"
})
@XmlRootElement(name = "stats")
public class Stats {

    @XmlElement(required = true)
    protected Rating rating;
    @XmlAttribute
    protected String maxplayers;
    @XmlAttribute
    protected String minplayers;
    @XmlAttribute(required = true)
    protected String numowned;
    @XmlAttribute
    protected String playingtime;

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link Rating }
     *     
     */
    public Rating getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rating }
     *     
     */
    public void setRating(Rating value) {
        this.rating = value;
    }

    /**
     * Gets the value of the maxplayers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxplayers() {
        return maxplayers;
    }

    /**
     * Sets the value of the maxplayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxplayers(String value) {
        this.maxplayers = value;
    }

    /**
     * Gets the value of the minplayers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinplayers() {
        return minplayers;
    }

    /**
     * Sets the value of the minplayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinplayers(String value) {
        this.minplayers = value;
    }

    /**
     * Gets the value of the numowned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumowned() {
        return numowned;
    }

    /**
     * Sets the value of the numowned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumowned(String value) {
        this.numowned = value;
    }

    /**
     * Gets the value of the playingtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayingtime() {
        return playingtime;
    }

    /**
     * Sets the value of the playingtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayingtime(String value) {
        this.playingtime = value;
    }

}
